version: 2

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  concurrency: 4
  build-tags:
    - integration
  allow-parallel-runners: true

linters:
  enable:
    - gocyclo
    - revive
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
    - gomodguard
    - godot
    - whitespace
    - wsl

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 10

  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G104

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/Shofyan/url-shortener

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  uniq-by-line: true

  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocritic

    - path: ".*\\.pb\\.go"
      linters:
        - all

    - path: vendor/.*
      linters:
        - all

    - linters:
        - lll
      source: "^//go:generate "

    - path: "cmd/.*/main\\.go"
      linters:
        - gocritic
      text: "exitAfterDefer"
